### ISSUE TITLE
number of columns of matrices must match (see arg 2)

### ISSUE THREAD

**Issue by frederickluser** [jonathandroth/staggered#12]
Dear Jonathan, Dear Pedro,

I am successfully using your estimator in my project, thank you very much for your great work! 

However, I want now to use the `HonestDiD` package. Thus, I want to also get the full covariance matrix from the staggered command. Thus, I run the following by changing `return_full_vcv` to `TRUE` (It works if I don't return the full matrix).

```
did.rs <- staggered(df = df, 
                    i = "id", t = "period", g = "G", y = "depVar", 
                    estimand = "eventstudy", eventTime = -6:6,
                    return_full_vcv = TRUE) # RS estimator
```

But now I get the error mentioned in the title: _number of columns of matrices must match (see arg 2)._ 

Do you have any idea whether this could be a problem of the function, or is it more likely something related to my data?

Thanks and best, Frederic

**Comment by jonathandroth** [comment]
Hi Frederic,

Thanks for your email! I would guess it's probably a bug on my part... Do
you have a dataset (or synthetic example) that you can share that produces
this error?

Thanks!

J
