### ISSUE TITLE
Stata package error message

### ISSUE THREAD

**Issue by jvglb** [jonathandroth/staggered#3]
Possible this is user error, but in running the Stata example code on the example dataset generated  error: "variable c2 not found" 

after: 
 staggered, y("complaints") g("first_trained") t("period") i("uid") estimand("simple") 
 
Same error replicated when varying estimand()

**Comment by jonathandroth** [comment]
There appear to be some issues with the beta version of rcall. Can you try:

github uninstall rcall
github install haghish/rcall, stable
github install jonathandroth/staggered_stata
clear all

Then try running staggered again, and let me know if that works?

**Comment by jvglb** [comment]
Fixed!

**Comment by jonathandroth** [comment]
Awesome! I've updated the install instructions to install the stable version. Thanks for bringing this to our attention :)
