### ISSUE TITLE
R dependency mistake

### ISSUE THREAD

**Issue by timmens** [jonathandroth/staggered#6]
Hey, I wanted to use your package using conda (to run it in a notebook) and ran into some errors. Pretty sure its the R dependency [here](https://github.com/jonathandroth/staggered/blob/47188565498c8e41b3320008ec4ed89707d5bf5c/DESCRIPTION#L22). I forked your repo, fixed it to 3.5.0 instead of 3.50 and it works smoothly.

Keep up the great work!

Best, Tim

**Comment by jonathandroth** [comment]
Fixed. Thank you!
